# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Minder
email: kminder(at)apache(dot)org
description: > # this means to ignore newlines until "baseurl:"
  Apache Knox tips and tutorials
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kminder.github.io/" # the base hostname & protocol for your site
future: false
twitter_username: minderit
github_username:  kminder

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

#markdown: kramdown
#kramdown:
#  input: GFM